paul_maxwell_homework_homepage:
    pattern:  /
    defaults: { _controller: PaulMaxwellHomeworkBundle:Default:index }

paul_maxwell_homework_about:
    pattern: /about
    defaults: { _controller: PaulMaxwellHomeworkBundle:Default:about }

paul_maxwell_homework_contact:
    pattern: /contact
    defaults: { _controller: PaulMaxwellHomeworkBundle:Default:contact }
