parameters:
#    paul_maxwell_homework.example.class: PaulMaxwell\HomeworkBundle\Example

services:
#    paul_maxwell_homework.example:
#        class: %paul_maxwell_homework.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
